### ISSUE TITLE
Can't start webapp - huge amount of errors

### ISSUE THREAD

**Issue by darvark** [coulisse/spiderweb#70]
Can't start app with Python 3.10,3.11,3.12 nor in docker.
There is huge amount of errors in code starting from this one

```
2024-08-19 15:50:32,326 [ERROR] (qry.py) Table 'dxcluster.spot' doesn't exist
Traceback (most recent call last):
  File "/app/webapp.py", line 160, in <module>
    heatmap_cbp = ContinentsBandsProvider(logger, qm, continents_cq, band_frequencies)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/plot_data_provider.py", line 52, in __init__
    super().__init__(logger, qm, continents, bands)
  File "/app/lib/plot_data_provider.py", line 41, in __init__
    self.refresh()
  File "/app/lib/plot_data_provider.py", line 163, in refresh
    qry_data = self.__load_data(self.bands, self.continents)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/plot_data_provider.py", line 111, in __load_data
    data = self.qm.get_data()
           ^^^^^^^^^^^^^^^^^^
  File "/app/lib/qry.py", line 68, in get_data
    return self.__data
           ^^^^^^^^^^^
AttributeError: 'query_manager' object has no attribute '_query_manager__data'. Did you mean: '_query_manager__cnxpool'?

```

And 
```
2024-08-19 15:56:25,999 [ERROR] (qry.py) Table 'dxcluster.spot' doesn't exist
Traceback (most recent call last):
  File "/app/webapp.py", line 160, in <module>
    heatmap_cbp = ContinentsBandsProvider(logger, qm, continents_cq, band_frequencies)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/plot_data_provider.py", line 52, in __init__
    super().__init__(logger, qm, continents, bands)
  File "/app/lib/plot_data_provider.py", line 41, in __init__
    self.refresh()
  File "/app/lib/plot_data_provider.py", line 163, in refresh
    qry_data = self.__load_data(self.bands, self.continents)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/plot_data_provider.py", line 112, in __load_data
    if len(data) == 0:
       ^^^^^^^^^
TypeError: object of type 'ConnectionPool' has no len()
```

And 
```
2024-08-19 15:57:24,147 [INFO] (plot_data_provider.py) query done
Traceback (most recent call last):
  File "/app/webapp.py", line 160, in <module>
    heatmap_cbp = ContinentsBandsProvider(logger, qm, continents_cq, band_frequencies)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/plot_data_provider.py", line 52, in __init__
    super().__init__(logger, qm, continents, bands)
  File "/app/lib/plot_data_provider.py", line 41, in __init__
    self.refresh()
  File "/app/lib/plot_data_provider.py", line 166, in refresh
    data_de = self.__normalize_continent(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/plot_data_provider.py", line 124, in __normalize_continent
    for i, item_data in enumerate(data_list):
                        ^^^^^^^^^^^^^^^^^^^^
TypeError: 'ConnectionPool' object is not iterable

```

those two latest  erros  exists in allmost whole plot_data_provider.py file. Tested on Ubuntu and ElementaryOS

**Comment by coulisse** [comment]
I think the problem is relatet to dxcluster that is not configured to write mariadb.
Please check if dxcluster database is writed by dxcluster
